
SET(PERL_TMP_D_HEADER
  e_os.h
  crypto/cryptlib.h 
#  crypto/buildinf.h
  crypto/md32_common.h
	crypto/o_time.h
  crypto/o_str.h                                        
  crypto/o_dir.h
  crypto/md4/md4_locl.h
  crypto/md5/md5_locl.h
  crypto/sha/sha_locl.h
  crypto/ripemd/rmd_locl.h
  crypto/ripemd/rmdconst.h
  crypto/des/des_locl.h
  crypto/des/rpc_des.h
  crypto/des/spr.h
  crypto/des/des_ver.h
  crypto/rc2/rc2_locl.h
  crypto/rc4/rc4_locl.h
  crypto/idea/idea_lcl.h
  crypto/bf/bf_pi.h
  crypto/bf/bf_locl.h
  crypto/cast/cast_s.h
  crypto/cast/cast_lcl.h
  crypto/aes/aes_locl.h
  crypto/camellia/cmll_locl.h
  crypto/seed/seed_locl.h
  crypto/modes/modes_lcl.h
  crypto/bn/bn_lcl.h
  crypto/bn/bn_prime.h
  crypto/dsa/dsa_locl.h
  crypto/ec/ec_lcl.h
  crypto/ecdh/ech_locl.h
  crypto/ecdsa/ecs_locl.h
  crypto/bio/bio_lcl.h
  crypto/objects/obj_dat.h
  crypto/objects/obj_xref.h
  crypto/evp/evp_locl.h
  crypto/asn1/asn1_locl.h
  crypto/x509v3/pcy_int.h
  crypto/cms/cms_lcl.h
  crypto/conf/conf_def.h
  crypto/ui/ui_locl.h
  crypto/whrlpool/wp_locl.h
  ssl/ssl_locl.h
  ssl/kssl_lcl.h
  engines/e_4758cca_err.c
  engines/e_4758cca_err.h
  engines/e_aep_err.c
  engines/e_aep_err.h
  engines/e_atalla_err.c
  engines/e_atalla_err.h
  engines/e_cswift_err.c
  engines/e_cswift_err.h
  engines/e_gmp_err.c
  engines/e_gmp_err.h
  engines/e_chil_err.c
  engines/e_chil_err.h
  engines/e_nuron_err.c
  engines/e_nuron_err.h
  engines/e_sureware_err.c
  engines/e_sureware_err.h
  engines/e_ubsec_err.c
  engines/e_ubsec_err.h
  engines/e_capi_err.c
  engines/e_capi_err.h
)

SET(OPENSSL_PERL_APPS_HEADER
  apps/apps.h
  apps/progs.h
  apps/s_apps.h
  apps/testdsa.h
  apps/testrsa.h
)

SET(PERL_INCO_D_HEADER 
  e_os2.h
  crypto/crypto.h
  crypto/opensslv.h
  crypto/opensslconf.h   
  crypto/ebcdic.h
  crypto/symhacks.h
  crypto/ossl_typ.h
  crypto/md4/md4.h
  crypto/md5/md5.h
  crypto/sha/sha.h
  crypto/mdc2/mdc2.h
  crypto/hmac/hmac.h
  crypto/cmac/cmac.h
  crypto/ripemd/ripemd.h
  crypto/des/des.h
  crypto/des/des_old.h
  crypto/rc2/rc2.h
  crypto/rc4/rc4.h
  crypto/idea/idea.h
  crypto/bf/blowfish.h
  crypto/cast/cast.h
  crypto/aes/aes.h
  crypto/camellia/camellia.h
  crypto/seed/seed.h
  crypto/modes/modes.h
  crypto/bn/bn.h
  crypto/rsa/rsa.h
  crypto/dsa/dsa.h
  crypto/dso/dso.h
  crypto/dh/dh.h
  crypto/ec/ec.h
  crypto/ecdh/ecdh.h
  crypto/ecdsa/ecdsa.h
  crypto/buffer/buffer.h
  crypto/bio/bio.h
  crypto/stack/stack.h
  crypto/stack/safestack.h
  crypto/lhash/lhash.h
  crypto/rand/rand.h
  crypto/err/err.h
  crypto/objects/objects.h
  crypto/objects/obj_mac.h
  crypto/evp/evp.h
  crypto/asn1/asn1.h
  crypto/asn1/asn1_mac.h
  crypto/asn1/asn1t.h
  crypto/pem/pem.h
  crypto/pem/pem2.h
  crypto/x509/x509.h
  crypto/x509/x509_vfy.h
  crypto/x509v3/x509v3.h
  crypto/cms/cms.h
  crypto/conf/conf.h
  crypto/conf/conf_api.h
  crypto/txt_db/txt_db.h
  crypto/pkcs7/pkcs7.h
  crypto/pkcs12/pkcs12.h
  crypto/comp/comp.h
  crypto/engine/engine.h
  crypto/ocsp/ocsp.h
  crypto/ui/ui.h
  crypto/ui/ui_compat.h
  crypto/krb5/krb5_asn.h
  crypto/pqueue/pqueue.h
  crypto/whrlpool/whrlpool.h
  crypto/ts/ts.h
  crypto/srp/srp.h
  ssl/ssl.h
  ssl/ssl2.h
  ssl/ssl3.h
  ssl/ssl23.h
  ssl/tls1.h
  ssl/dtls1.h
  ssl/kssl.h
  ssl/srtp.h
)

SET(ASM_FILE_LIST
  crypto/x86cpuid.pl
  crypto/md5/asm/md5-586.pl
  crypto/sha/asm/sha1-586.pl
  crypto/sha/asm/sha256-586.pl
  crypto/sha/asm/sha512-586.pl
  crypto/ripemd/asm/rmd-586.pl
  crypto/des/asm/des-586.pl
  crypto/des/asm/crypt586.pl
  crypto/rc4/asm/rc4-586.pl
  crypto/bf/asm/bf-586.pl
  crypto/cast/asm/cast-586.pl
  crypto/aes/asm/aes-586.pl
  crypto/aes/asm/vpaes-x86.pl
  crypto/aes/asm/aesni-x86.pl
  crypto/camellia/asm/cmll-x86.pl
  crypto/modes/asm/ghash-x86.pl
  crypto/bn/asm/bn-586.pl
  crypto/bn/asm/co-586.pl
  crypto/bn/asm/x86-mont.pl
  crypto/bn/asm/x86-gf2m.pl
)  
